### ISSUE TITLE
System.OverflowException: 'Arithmetic operation resulted in an overflow.'

### ISSUE THREAD

**Issue by kumarmageshr** [Noksa/WebDriver.Screenshots.Extensions#12]
Please find the code 
```
             IWebDriver driver;
            driver = new ChromeDriver(System.IO.Directory.GetCurrentDirectory() + "\\driver");
            driver.Url = "http://www.seleniumstutorial.com/taking-screenshot-using-c-selenium/";

            var scMaker = new ScreenshotMaker();
            var cutFooterDecorator = new CutterDecorator(scMaker);
            cutFooterDecorator.SetCuttingStrategy(new CutElementHeightOnEntireWidthThenCombine(By.Id("footer")));
            var vcd = new VerticalCombineDecorator(cutFooterDecorator);
            var screenArrBytes = driver.TakeScreenshot(vcd);
```
While excute above code in **TakeScreenshot** return following error.
"Arithmetic operation resulted in an overflow."

**Comment by kumarmageshr** [comment]
Can you check below Url also. 
[https://edition.cnn.com/entertainment](url)

**This is different one**
Error Message: "OpenQA.Selenium.WebDriverException: 'Script returned a value, but the result could not be cast to the desired type'"

**Comment by Noksa** [comment]
@kumarmageshr 
Confirmed. This is a bug (first test-case).

**Comment by Noksa** [comment]
@kumarmageshr 
> Can you check below Url also.
> [https://edition.cnn.com/entertainment](url)

Can you please give more info about this error? 
Browser/resolution/code.

**Comment by kumarmageshr** [comment]
> @kumarmageshr
> 
> > Can you check below Url also.
> > [https://edition.cnn.com/entertainment](url)
> 
> Can you please give more info about this error?
> Browser/resolution/code.

URL : https://edition.cnn.com/entertainment
While running the above page its return below.

Error Message: "OpenQA.Selenium.WebDriverException: 'Script returned value, but the result could not be cast to the desired type'"

**Comment by Noksa** [comment]
@kumarmageshr 
Please, provide a code which throws error.
At this page I can’t find element with Id “footer”.

**Comment by kumarmageshr** [comment]
> @kumarmageshr
> Please, provide a code which throws error.
> At this page I can’t find element with Id “footer”.

I didn't provide footer id.. without footer id can we use it ?

**Comment by Noksa** [comment]
@kumarmageshr 
In this case, I do not understand what kind of error you are talking about.
What code causes an error?
Without the code, I can not help, because I do not understand how to reproduce error.
I fixed first bug, the question is about the CNN site.
