### ISSUE TITLE
Doesn't work for IE driver

### ISSUE THREAD

**Issue by dkritsky** [Noksa/WebDriver.Screenshots.Extensions#14]
This is what I get when I try to take a screenshot with the Internet Explorer driver:

    OpenQA.Selenium.WebDriverException : JavaScript error

Relevant parts of the stacktrace:

     at OpenQA.Selenium.Support.Extensions.WebDriverExtensions.ExecuteJavaScript[T](IWebDriver driver, String script, Object[] args)
     at WDSE.Helpers.JQueryHelper.GetAllElementsWithScrollbars(IWebDriver driver)
     at WDSE.Helpers.JQueryHelper.GetElementWithActiveScrollBar(IWebDriver driver)
     at WDSE.Decorators.VerticalCombineDecorator.CombineScreenshots(IWebDriver driver)
     at WDSE.Decorators.VerticalCombineDecorator.MakeScreenshot(IWebDriver driver)
     at WDSE.ExtensionMethods.TakeScreenshot(IWebDriver driver, IScreenshotStrategy strategy)

I believe this is because IE doesn't support some of the latest Javascript features.
eg. 
- const keyword
- let keyword
- spread operator (...array)
- string interpolation \`${foobar}\`

**Comment by Noksa** [comment]
@dkritsky 
Hello! Yep, the possibility of using in IE was not taken in point during develop.
Also, in addition to those indicated by you, there are other unsupported things in IE, like this: https://developer.mozilla.org/en-US/docs/Web/API/Document/scrollingElement

**Comment by Noksa** [comment]
@dkritsky 
Im uploaded the beta version of the package with IE support.
Could you download it and give feedback - does everything work correctly?
Link: https://www.nuget.org/packages/Noksa.WebDriver.ScreenshotsExtensions/0.1.0-beta

**Comment by dkritsky** [comment]
@Noksa 
I'm finding that the `VerticalCombineDecorator` isn't scrolling the browser page for me (although still taking a screenshot). However I did notice it does work for some websites: eg. https://www.microsoft.com

And for some websites it just crashes:

     at OpenQA.Selenium.Support.Extensions.WebDriverExtensions.ExecuteJavaScript[T](IWebDriver driver, String script, Object[] args)
     at WDSE.Helpers.JQueryHelper.CheckJQueryOnPage(IWebDriver driver)
     at WDSE.ExtensionMethods.TakeScreenshot(IWebDriver driver, IScreenshotStrategy strategy)

eg.
- https://www.apple.com
- https://angular.io
- https://reactjs.org

I'll probably investigate what's different on the site I'm looking at.

**Comment by Noksa** [comment]
@dkritsky 
The difference is that on some sites the JQuery is already connected, but somewhere not.
In the Internet Explorer, when you try to call a some JQuery method, an unexpected exception text appear (not like at Chrome).
I'm fixed it, scrolling now works at this sites, you can check it: https://www.nuget.org/packages/Noksa.WebDriver.ScreenshotsExtensions/0.1.1-beta

**Comment by dkritsky** [comment]
@Noksa 
So I found out the problem that I was getting on my site. It's the same problem as on:
- https://getbootstrap.com/docs/3.4/javascript/

It looks like `GetAllElementsWithScrollBars` does not return the html document for Bootstrap v3. The scrollbar can hide, which makes the window and the document element have the same width:

    if (element.tagName === document.scrollingElement.tagName && typeof window.innerWidth === "number") {
        return window.innerWidth > document.documentElement.clientWidth;
    }

Can we turn the greater than, to a greater than or equal? That fixes things for me.

**Comment by Noksa** [comment]
@dkritsky 
I completely changed the condition for checking the main scrollbar.
https://www.nuget.org/packages/Noksa.WebDriver.ScreenshotsExtensions/0.1.2-beta

**Comment by dkritsky** [comment]
@Noksa 
Tested, and working.
