### ISSUE TITLE
Noksa.WebDriver.ScreenshotsExtensions for Selenium Webdriver 3.8.0

### ISSUE THREAD

**Issue by venkivb4u** [Noksa/WebDriver.Screenshots.Extensions#18]
Hello,

Currently, I am using Selenium webdriver 3.8.0 and Noksa.WebDriver.ScreenshotsExtensions is not supported for the same. Is it possible to make this work for Selenium webdriver 3.8.0?

Thanks!
Venky.

**Comment by Noksa** [comment]
Hello.
Try this version: https://www.nuget.org/packages/Noksa.WebDriver.ScreenshotsExtensions/0.1.4.5-beta1

**Comment by Noksa** [comment]
Done in 0.1.5
