### ISSUE TITLE
.NET Standard Support

### ISSUE THREAD

**Issue by luizcarlosfaria** [Noksa/WebDriver.Screenshots.Extensions#19]
Read on Nuget.org we can see dependencies about:
- .NETFramework 4.5.2
- .NETFramework 4.6
- .NETFramework 4.6.1
- .NETFramework 4.6.2
- .NETFramework 4.7
- .NETFramework 4.7.1
- .NETFramework 4.7.2

And has no target for .NET Standard 2. 

Do you have any roadmap to provide a .NET Standard target?

**Comment by luizcarlosfaria** [comment]
After create this issue i've fork your project and i've create a pull request #20  to address .NET Standard.

**Comment by Noksa** [comment]
Hello, @luizcarlosfaria 
Thanks for contribute :)
