### ISSUE TITLE
Fixed navigation menu screenshot issue

### ISSUE THREAD

**Issue by venkivb4u** [Noksa/WebDriver.Screenshots.Extensions#22]
I have a application that has a fixed navigation menu. When it takes screenshot, the menu appears on all the segment of the screenshot. Please suggest how to fix or handle it?

Thanks!
Venky.

**Comment by Noksa** [comment]
Hello, @venkivb4u!
You can delete an any element before taking a screenshot.

Just use `CutterDecorator`: https://github.com/Noksa/WebDriver.Screenshots.Extensions/wiki/Decorators#CutterDecorator

Example: https://github.com/Noksa/WebDriver.Screenshots.Extensions/wiki/Cut-strategies

Or you can hide any element before taking a screenshot.
After taking the screenshot, the hidden element will be visible again.
This strategy may cause the screenshots to be incorrectly glued, as layout may change.

Example: https://github.com/Noksa/WebDriver.Screenshots.Extensions/wiki/Hide-elements
