### ISSUE TITLE
Error using new Selenium 4 Edge driver and TakeScreenshot method

### ISSUE THREAD

**Issue by 3KMedialab** [Noksa/WebDriver.Screenshots.Extensions#28]
When I execute this code: 

```
var maker = new ScreenshotMaker();
maker.RemoveScrollBarsWhileShooting();
var vertical = new VerticalCombineDecorator(maker);
var data = DriverManagerContext.GetDriverManager().GetDriver().TakeScreenshot(vertical);
```

I get the following exception when calling TakeScreenshot method using a Selenium 4 Edge driver:

Unable to cast object of type 'OpenQA.Selenium.Edge.EdgeDriver' to type 'OpenQA.Selenium.Remote.RemoteWebDriver'.

**Comment by Noksa** [comment]
https://www.nuget.org/packages/Noksa.WebDriver.ScreenshotsExtensions/0.1.5.4
